### PR TITLE
Delete unnecessary files

### PR DESCRIPTION
**Pull request by rivercory**
@tushargupta1504 Deleted unnecessary Bootstrap files!

### CODE REVIEW

**Review by SAMluci666 — COMMENTED** [review]
Did you make the necessary changes in the head tag of some files that used these files?

**Comment by rivercory** [comment]
@SAMluci666 Nobody used this element.

**Comment by SAMluci666** [comment]
@rivercory Check out physician.html for start, there are at least two more files that use these files.

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @tushargupta1504

Regards,
Community Manager Gssoc-ext

**Pull request merged**
