### PR TITLE
✨ Dark mode toggle created ✨  (issue #155)

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the dark mode toggle switch has been implemented , can you please confirm the PR. thank you :)

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
https://github.com/user-attachments/assets/b73dfa63-6b89-4d6c-9eb7-07b5a465a143

**Comment by T-Rahul-prabhu-38** [comment]
can you please assign the level as well, thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@sanjay-kv  can you please review this PR.

**Comment by tushargupta1504** [comment]
image

**Pull request closed without merging**
