### PR TITLE
Added FAQ Section

### PR DESCRIPTION
**Pull request by Mansi07sharma**
Check it I made it perfect for your website if you want additional one then tell me.

#632

### CODE REVIEW

**Comment by Mansi07sharma** [comment]
@tushargupta1504 kindly review it

**Comment by Mansi07sharma** [comment]
@tushargupta1504 Kindly merge it

**Comment by Mansi07sharma** [comment]
@tushargupta1504 Kindly merge it. 
You assigned it to me and I pull requested on time but you have not even merged it. Please merge it.
I have seen that you have merged someone else's merge request without even assign to them and my not even see?

Why this? @tushargupta1504

**Comment by tushargupta1504** [comment]
image

**Pull request closed without merging**
