### PR TITLE
Added functionality to contact us page

### PR DESCRIPTION
**Pull request by ananyag309**
#12

### CODE REVIEW

**Comment by ananyag309** [comment]
donee

**Comment by ananyag309** [comment]
@tushargupta1504 please add gssoc ext and level label

**Comment by ananyag309** [comment]
@tushargupta1504 please add hactoberfest label

**Comment by tushargupta1504** [comment]
this is appearing two times please remove it
image

**Comment by ananyag309** [comment]
ok letme check

**Comment by ananyag309** [comment]
codee
ig i changed only this part of code please let me know what part to be deleted

**Pull request merged**
