### PR TITLE
Updated Nearby Section

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
- Created better interface by restructuring the nearby page to block style
- images, clickable names 
- @tushargupta1504 
Screenshot 2024-10-04 112523

### CODE REVIEW

**Comment by Adarsh-Chaubey03** [comment]
My PR was closed without merging. Could you let me know why? I’m new to open source and any feedback would be really helpful. Thanks!

**Comment by Adarsh-Chaubey03** [comment]
@tushargupta1504  unable to see the reason for pr being closed unmerged

**Comment by tushargupta1504** [comment]
image
the reason was that it has some conflicts kindly fix them all and raise a new one

**Comment by Adarsh-Chaubey03** [comment]
created #240

**Pull request closed without merging**
