### PR TITLE
Added the Follow us section of Social Media links also Changed the Footer Section Appearance

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
Added the Follow us section of Social Media links

(BEFORE)
Screenshot 2024-10-09 125543

(AFTER)
Screenshot 2024-10-09 125518

ALSO, CHANGED THE FOOTER SECTION APPEARANCE

(BEFORE)
Screenshot 2024-10-09 125518

(AFTER)
Screenshot 2024-10-10 155017

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@tushargupta1504 plz merge my pull request and add the LABLES to my pull request

**Comment by PatelHarsh2006** [comment]
@tushargupta1504 lease assign it LEVEL2 label

**Comment by tushargupta1504** [comment]
image

**Comment by PatelHarsh2006** [comment]
> image

@tushargupta1504 Please Reopen this Pull Request I will Solve this Conflicts

**Pull request closed without merging**
